#!/usr/bin/env python3
"""Copy _shared/jev_provider.py into every app folder.

Apps are deliberately standalone -- you can clone one folder out of this repo
and run it with no repo-root imports. That means the client is duplicated, so
it is GENERATED rather than abstracted: edit _shared/, then run this.

    python scripts/sync_provider.py          # write the copies
    python scripts/sync_provider.py --check  # fail if any copy is stale (CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "_shared" / "jev_provider.py"
TARGET_DIRS = sorted(p for p in (ROOT / "apps").glob("*") if p.is_dir())

BANNER = "# GENERATED by scripts/sync_provider.py -- edit _shared/jev_provider.py instead.\n"


def main() -> int:
    check_only = "--check" in sys.argv
    if not SOURCE.is_file():
        print(f"missing source: {SOURCE}", file=sys.stderr)
        return 1
    if not TARGET_DIRS:
        print("no apps yet; nothing to sync")
        return 0

    payload = BANNER + SOURCE.read_text(encoding="utf-8")
    stale: list[Path] = []

    for app_dir in TARGET_DIRS:
        target = app_dir / "jev_provider.py"
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == payload:
            continue
        stale.append(target.relative_to(ROOT))
        if not check_only:
            target.write_text(payload, encoding="utf-8")
        # Each app also needs providers.toml beside it to stay forkable.
        app_config = app_dir / "providers.toml"
        if not check_only and not app_config.is_file():
            app_config.write_text((ROOT / "providers.toml").read_text(encoding="utf-8"), encoding="utf-8")

    if check_only and stale:
        print("stale copies (run: python scripts/sync_provider.py):", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1

    print(f"synced jev_provider.py -> {len(TARGET_DIRS)} app(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
